  version: "3"
  services:
    db:
      container_name: pg-prod
      image: postgres:9.6
      networks:
        - prod_net_back
      environment:
        - POSTGRES_PASSWORD=passwd
        - POSTGRES_DB=tasks
      volumes:
        - prod_postgresql:/var/lib/postgresql
        - prod_postgresql_data:/var/lib/postgresql/data

    backend:
      container_name: backend-prod
      image: back_prod:build_${BUILD_NUMBER}
      build:
        context: .
        args:
          - WAR_FILE=target/tasks-backend.war
          - CONTEXT=tasks-backend
      networks:
        - prod_net_back
      ports:
        - 9998:8080
      environment:
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
        - DATABASE_USER=postgres
        - DATABASE_PASSWD=passwd
        #- DATABASE_UPDATE=none
      depends_on:
        - db

    sonarqube:
      container_name: sonar
      image: sonarqube:7.9.2-community
      ports:
        - "9000:9000"
      networks:
        - sonarnet
      environment:
        - sonar.jdbc.url=jdbc:postgresql://pg-sonar:5432/sonar
      depends_on:
        - pg-sonar
      volumes:
        - sonarqube_conf:/opt/sonarqube/conf
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

    pg-sonar:
      container_name: pg-sonar
      image: postgres:9.6
      networks:
        - sonarnet
      environment:
        - POSTGRES_USER=sonar
        - POSTGRES_PASSWORD=sonar
      volumes:
        - prod_postgresql:/var/lib/postgresql
        - prod_postgresql_data:/var/lib/postgresql/data

  networks:
    prod_net_back:
    sonarnet:

  volumes:
    prod_postgresql:
    prod_postgresql_data:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_bundled-plugins:
